### PR TITLE
Add slides for array find from right

### PR DESCRIPTION
**Pull request by Kingwl**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
before the 10 day deadline, you're welcome to push things like this directly up as a commit.

**Comment by Kingwl** [comment]
Okay. Thanks!

**Comment by zloirock** [comment]
@Kingwl 2 copies of `Array.prototype.findLast` spec draft in slides instead of `Array.prototype.find`.

**Comment by Kingwl** [comment]
Thanks! Fixed.

**Pull request merged**
