### PR TITLE
Slides for shared memory presentation

### PR DESCRIPTION
**Pull request by lars-t-hansen**

### CODE REVIEW

**Comment by leobalter** [comment]
On my understanding, @allenwb suggested we should have the slides along with the meeting notes.

I don't have a preference I would die for, but I believe we should have a final and consistent decision on this. One single place is batter than many.

**Comment by rwaldron** [comment]
Sorry, this format is not acceptable. Slides that aren't hosted on some web platform need to be provided as PDF _only_.

**Comment by ljharb** [comment]
What is ODP?

**Comment by leobalter** [comment]
Open Document Presentation, used w/ OpenOffice

**Comment by rwaldron** [comment]
For context, slides are entered into the official record with Ecma

**Comment by lars-t-hansen** [comment]
I've added a PDF, I'll submit a PR to fix the link.

**Comment by rwaldron** [comment]
Thank you

**Pull request merged**
