### PR TITLE
🔥 remove image

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Comment by ljharb** [comment]
why remove it?

**Comment by ctcpip** [comment]
one might argue we shouldn't store corporate campus maps in the agenda repo

**Comment by ljharb** [comment]
google earth exists, and if a campus map that's been public for 7 years is a security issue that suggests bigger problems :-) did someone at paypal request this?

**Comment by littledan** [comment]
This seems like a privacy-driven removal suggestion. @SaminaHusain is responsible for such matters legally for Ecma, as our GDPR point-person (not sure of the official term). Maybe she will have thoughts here. IMO this would be a good patch to land.

**Review by robpalme — APPROVED** [review]

**Pull request merged**
