### PR TITLE
Update 07.md

### PR DESCRIPTION
**Pull request by ecmageneva**
I try to introduce my points into the agenda.
No idea how to make 3.1 instead of 4...

### CODE REVIEW

**Comment by bterlson** [comment]
Sorry missed this pr. Will add these items tomorrow since this won't apply cleanly anymore.

**Comment by ecmageneva** [comment]
Thanks...
But how could I have made the edits myself?
This looks very complicated.

**Comment by bterlson** [comment]
Easiest way to do it would have been to just make the edits again starting from the most recent version and ditch this PR (which is what I'm doing for you now). There are fancier ways...

Also, numbered lists in this format (called Markdown) start with any digit and a dot and are numbered automatically. You make sublists by indenting. Example:

```
1. first
    1. first first
    1. second first
1. second
```

1. first
    1. first first
    1. second first
1. second

**Comment by bterlson** [comment]
Ok the latest agenda should contain your items. Please take a look.

**Comment by ecmageneva** [comment]
Brian,
many thanks that already helps a lot.
But I would also like to play a bit with Github in order that I get a better feeling what it is and how it works. Where I have my next difficulties is that I have installed Github for Windows, but I do not find how I could make the local copy of the agenda on which I can make the changes, and after how to feed it back to Github.
Kind regards,
Istvan

**Comment by bterlson** [comment]
I think it's best to not take a local copy for just editing the agenda. You can do it entirely from the website. Here are the instructions: https://help.github.com/articles/editing-files-in-another-user-s-repository/.

**Pull request closed without merging**
