### PR TITLE
add elections

### PR DESCRIPTION
**Pull request by codehag**

### CODE REVIEW

**Comment by jridgewell** [comment]
:Ahem: `(+0)**-1`. 😉

**Comment by ljharb** [comment]
the forced parens are only for a negative base :-p

**Comment by jridgewell** [comment]
It covers any unary operator. https://astexplorer.net/#/gist/97005767c00a06690c005a48d4805e8c/a9fcd4d3da752edb48a907eb4dc6b13da506724c

**Comment by ljharb** [comment]
ah. i'd meant the + to not be part of the expression; i've fixed my comment :-p

**Pull request merged**
