### PR TITLE
Add link to slides for JSL

### PR DESCRIPTION
**Pull request by mattijs**
Slides for JavaScript Standard Library agenda item.

### CODE REVIEW

**Comment by zloirock** [comment]
> Polyfilling Scenarios
> import-maps should handle those

Are you serious?

**Comment by ljharb** [comment]
@zloirock this isn't the place to comment on the proposal itself, please do that on its repo.

**Comment by zloirock** [comment]
@ljharb it's a comment for slides, not for proposal.

**Comment by ljharb** [comment]
the content of the slides should also be discussed on the proposal repo (and in this case, already has been brought up)

**Pull request merged**
