### PR TITLE
approving a replacement name for Array.prototype.flatten (not smoosh)

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
So looking forward to this.

**Comment by jdalton** [comment]
So rad if folks tackled the root cause instead of bikeshedding names.

**Comment by littledan** [comment]
I'd suggest that you start the discussion of this name with TC39 before the meeting somehow so we can get further in the committee discussion.

**Comment by michaelficarra** [comment]
@littledan https://github.com/tc39/Reflector/issues/142

**Pull request merged**
