### PR TITLE
Request a 30 minute slot for Module Keys proposal up from 15 minutes

### PR DESCRIPTION
**Pull request by mikesamuel**
Per discussion with @littledan in https://github.com/tc39/agendas/pull/323

### CODE REVIEW

**Comment by michaelficarra** [comment]
@mikesamuel Given the potential breadth of this topic, I'd recommend a still longer timebox, or even no timebox at all.

**Comment by mikesamuel** [comment]
@michaelficarra I'll put together some slides and time myself.  Do you have a sense for what might be the most controversial parts?

**Comment by littledan** [comment]
I'm not sure if a longer timebox is needed. It's true that it could be difficult to deeply discuss everything completely in 30 minutes, or even an hour, but sometimes the first discussion about a topic is more an introduction, to motivate research and discussion offline. A non-timeboxed presentation risks falling off the bottom of the agenda and also engaging only the small percentage of the committee members who take the time to think deeply about the proposal before the meeting.

**Comment by leobalter** [comment]
I strongly believe 30 minutes won't be enough for this topic, as I believe it's at least worth having a non superficial discussion over this topic if this will ever get to advance in the stage process.

Although, the current timebox should be enough to present and start some discussions, even if not enough to capture all the questions and concerns.

**Comment by leobalter** [comment]
@mikesamuel are you sure you want to add this for the meeting in May and not the next in March?

I just want to confirm this to avoid any frustration.

In the meanwhile, @dherman and @bmeck you might be interested in this topic.

**Comment by mikesamuel** [comment]
@leobalter I'm excited to talk about this, but I won't be able to make it to London in March.  At best I could do a call-in, but I am not good at relating unfamiliar concepts over the phone.   I live one state over from New York state, so can easily make it to the May meeting.

**Comment by leobalter** [comment]
sure thing, I'm looking forward to discuss this in May.

**Comment by littledan** [comment]
@mikesamuel A call might not be a bad idea anyway, e.g., to briefly introduce the concept. I've introduced proposals and advanced via a call before (e.g. private methods went straight to Stage 2 while I was on the other side of the pond) so I think it can be workable.

**Pull request merged**
