### PR TITLE
Add slides for Record and Tuple update July 2022

### PR DESCRIPTION
**Pull request by acutmore**
Adds link to current R/T slides and issues.

### CODE REVIEW

**Comment by ljharb** [comment]
it might be nice to host the slides on github, so they can be accessed long term?

**Comment by rricard** [comment]
> it might be nice to host the slides on github, so they can be accessed long term?

Should we have a `tc39/slides` repository for that matter?

**Comment by ljharb** [comment]
That might be a good idea; alternatively it could be stored in the notes repo or here.

**Review by ljharb — APPROVED** [review]

**Comment by bakkot** [comment]
Notes repo is what we used to use: https://github.com/tc39/notes/search?p=3&q=extension%3Apdf

**Pull request merged**
