### PR TITLE
Sign bit

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by rwaldron** [comment]
@jfbastien @bterlson this is missing an actual proposal to review. The linked thread doesn't clarify much about this topic.

**Comment by michaelficarra** [comment]
Since it doesn't appear to be seeking stage advancement (`0 === -0`), the details shouldn't be necessary.

**Comment by jfbastien** [comment]
I'll write something up over the next few days.
Yes, `Stage 0 === Stage -0` 😁
Motivated by Twitter thread with @BrendanEich: https://twitter.com/jfbastien/status/818880763953221632

**Comment by jfbastien** [comment]
@rwaldron preso here: #226

**Pull request merged**
