### PR TITLE
Update 05.md

### PR DESCRIPTION
**Pull request by littledan**
Link to proposed SIMD.js draft spec

### CODE REVIEW

**Comment by rwaldron** [comment]
@littledan where is the draft spec source? Specifically: if I need to file issues or pull requests to propose changes, what repo contains the document that I would make those changes or fixes in?

**Comment by ljharb** [comment]
Looks like https://github.com/littledan/littledan.github.io/blob/master/simd.html

**Comment by rwaldron** [comment]
That's what I thought as well, but then came across this: https://github.com/littledan/value-spec/blob/master/spec.html

**Comment by littledan** [comment]
Spec.html is the source, simd.html is the generated output.

**Comment by rwaldron** [comment]
Thanks.

**Comment by rwaldron** [comment]
@littledan I just noticed a link in that source, directing issues to be filed in yet another repo.

**Comment by littledan** [comment]
You're right, it's confusing to have these all in different repos. I actually have a copy of everything in John's repo. Let's say that the authoritative one is there, with the source at https://github.com/johnmccutchan/ecmascript_simd/blob/master/tc39/spec.html . My repo will just hold my own drafts.

**Comment by littledan** [comment]
On the other hand, the web link can still point to the same location, and I'll just make sure that the website is kept in sync with the authoritative copy in John's repo (since I don't know of any other ecmacscript_simd website for me to put them at).

**Pull request merged**
