### PR TITLE
Add agenda item about stage-1 null prop operator.

### PR DESCRIPTION
**Pull request by gisenberg**
Slides are in progress.

### CODE REVIEW

**Comment by bmeck** [comment]
LGTM

**Comment by concavelenz** [comment]
Was there an update on the slides?

**Comment by gisenberg** [comment]
Not yet, I'll get those in today.

**Comment by gisenberg** [comment]
@concavelenz @bmeck Quick heads up that I updated the slides. I was going through some prior discussion and also found mention of a formal proposal being put together by @claudepache about a year ago over [here](https://esdiscuss.org/topic/specifying-the-existential-operator-using-abrupt-completion) but couldn't find the output of that.

**Comment by claudepache** [comment]
@gisenberg see: https://github.com/claudepache/es-optional-chaining

**Comment by rwaldron** [comment]
"Elvis operator ?."

I ❤️ this name

**Comment by gisenberg** [comment]
@claudepache Thanks! I've added those links to the slides for discussion.

**Pull request merged**
