### PR TITLE
Add Optional Chaining to July 2019 Agenda

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by jridgewell** [comment]
We usually have projectors, so using a dark background for code slides makes them unreadable.

**Comment by DanielRosenwasser** [comment]
Will do - I also meant Stage 3, not Stage 4. Under the weather today. 😅

**Comment by DanielRosenwasser** [comment]
Should be fixed now.

**Comment by ljharb** [comment]
thanks, will merge once rebased

**Pull request merged**
