### PR TITLE
strikeout class fields agenda item

### PR DESCRIPTION
**Pull request by jeffmo**

### CODE REVIEW

**Comment by ljharb** [comment]
you may want to delete it - `~~` usually means it's been discussed

**Comment by jeffmo** [comment]
ok, updated

**Comment by flying-sheep** [comment]
so it wasn’t? :disappointed: 

what are we going to do now regarding jeffmo/es-class-fields-and-static-properties#26?

**Comment by michaelficarra** [comment]
January meeting is over. Let's close this.

**Comment by flying-sheep** [comment]
for people ending up here and wondering what’s going on:

automatic semicolon insertion (ASI) applies for the class fields as normal, so no semicolons required.

**Pull request merged**
