### PR TITLE
Add agenda item for optional-chaining updates.

### PR DESCRIPTION
**Pull request by gisenberg**

### CODE REVIEW

**Comment by littledan** [comment]
Should this be in the late agenda items bucket, or is that only for things that propose stage advancement?

**Comment by ljharb** [comment]
whoops, closed this by mistake

**Comment by ljharb** [comment]
@littledan That's only for things that propose stage advancement.

**Comment by ljharb** [comment]
Merged in cd101f49e9615ec39065c977f557e76f75ffdeac

**Pull request closed without merging**
