### PR TITLE
Propose / schedule Nova engine talk

### PR DESCRIPTION
**Pull request by aapoalas**
Invited by Luca and Dan E, a talk on an experimental engine interpreting the ECMAScript specification in a data-oriented way; the intention is to motivate and encourage new ways to look at the language.

The talk was given at Web Engines Hackfest and received a fair bit of interest and spawned this invitation to take the talk to TC39. The talk is approximately 25 minutes in length, though at WEHF the QA after took it to 37 minutes in total length. I was instructed to open a pull request to add the talk to the agenda to get the talk scheduled.

On the actual scheduling side, Wednesday 19th would work the best for me but any day is doable.

### CODE REVIEW

**Review by michaelficarra — APPROVED** [review]

**Comment by ljharb** [comment]
@aapoalas you may need to be registered as an observer and/or an invited expert in order to give this talk; has that been done? @lucacasonato, you may need to notify chairs and/or file an admin issue.

**Comment by aapoalas** [comment]
@ljharb At least an email has been sent to chairs.

**Comment by lucacasonato** [comment]
@ljharb Chairs are notified already and @SaminaHusain has already given the go-ahead.

**Comment by ljharb** [comment]
awesome, thanks for confirming :-)

**Comment by aapoalas** [comment]
> Aapo, Thank you for participating as an observer next week at the TC39 plenary. I look forward to your presentation. I want to clarify the date, I believe it is Wednesday 12th not Wednesday 19th (noted above). Is that correct?

Ah, yes indeed. My eyes skipped a week when writing the message. I'll fix the description.

**Comment by SaminaHusain** [comment]
perfect, thanks

**Comment by aapoalas** [comment]
@ryzokuken @ctcpip I head that I might be scheduled for Tuesday (tomorrow) at 13:00. That's mostly fine for me (Wednesday would still be better) but note that I am 150 kilometres away, so I need to know today if I need to be there tomorrow.

**Comment by ctcpip** [comment]
@aapoalas we are happy to move it to Wednesday or Thursday.  what works best for you?  also, presenting remotely is an option; it is not required to be there in person.

**Comment by aapoalas** [comment]
@ctcpip Wednesday would be best. I do prefer to give the talk in person, since I am only a train ride away anyway :)

**Comment by ctcpip** [comment]
@aapoalas great. the schedule has been updated. your topic is scheduled for ~10:30.  does that work?

**Comment by aapoalas** [comment]
Sure thing! Thank you <3

**Pull request merged**
