### PR TITLE
using root license as default for test files on test262

### PR DESCRIPTION
**Pull request by leobalter**
This is about a Test262 need consensus PR, I want to limit it to 15 minutes max and preferrably not address this item during the test262 updates, which I've got a lot of other things to mention.

### CODE REVIEW

**Comment by ljharb** [comment]
I won't be at the meeting, but having anything other than a single license at the root of the repo is redundant and ridiculous, so I hope we can move to that model in test262.

**Comment by leobalter** [comment]
It is such a hassle to address missing or confusing licensing on top of every test file when I'm reviewing PRs. I wanna stop being picky in my feedbacks. :)

**Comment by ljharb** [comment]
Totally. It's a super obsolete and archaic pattern to repeat metadata that's already in your version control software, or elsewhere in your repo, in every file - which includes creation/modification date, author(s), license, etc.

**Comment by littledan** [comment]
@ljharb This is a legal question; with certain past copyright law, such practices of omitting the copyright might not be acceptable, so I think it's a little excessive to call it "ridiculous", though the style proposed here is a growing trend and seems to work for many open source projects now.

**Comment by ljharb** [comment]
I've seen enough lawyers sign off on open source projects with a single license file that at the least, it's no longer an automatic legal issue - certainly it may have been in the past, when law hadn't caught up to technology.

**Pull request merged**
