### PR TITLE
Discuss Array.prototype.group

### PR DESCRIPTION
**Pull request by littledan**
Volunteers needed!

### CODE REVIEW

**Comment by ljharb** [comment]
I believe @jridgewell was waiting on compat data before adding this one.

**Comment by littledan** [comment]
@ljharb Is there any sort of effort ongoing to get compat data? I think we should at least have a status update, even if it's not conclusive yet.

**Comment by ljharb** [comment]
@littledan yes, that's what's being waited on.

**Comment by michaelficarra** [comment]
This was added out of order. Fixed in https://github.com/tc39/agendas/commit/c947ab82b3305349a61eafbfe6ec4f4d19661193.

**Comment by michaelficarra** [comment]
Also, @littledan please make sure you have a presenter listed before the meeting starts. If we don't have a presenter for each topic, I won't be able to approve the agenda.

**Pull request merged**
