### PR TITLE
Add Module Keys Stage 0 Strawman to agenda

### PR DESCRIPTION
**Pull request by mikesamuel**
Per [Entrance Criteria](https://tc39.github.io/process-document/) for Stage 1:

* [X] Identified “champion” who will advance the addition - Me
* [X] Prose outlining the problem or need and the general shape of a solution - See linked
* [X] Illustrative examples of usage - See linked
* [X] High-level API - See linked
* [X] Discussion of key algorithms, abstractions and semantics - See linked
* [ ] Identification of potential “cross-cutting” concerns and implementation challenges/complexity - Will pursue between now and May

### CODE REVIEW

**Comment by littledan** [comment]
This looks like a pretty large and well-thought-out proposal. Have you considered requesting a larger timebox to present it to the committee?

**Comment by mikesamuel** [comment]
@littledan Good point.  I hadn't.  Do you have an opinion on whether there's closer to 30 or 45 minutes of material to productively chew over?

**Comment by littledan** [comment]
Well, if you actually go over all of your material and the motivation, it might take an hour. I think 30 minutes would be enough if you want to give a light introduction and allow a little time for discussion.

**Comment by mikesamuel** [comment]
Yeah, I'll put in another PR.  I think most of the failure modes stuff, alternative approaches, and the relationship between proper cryptographic operators and this approach is best left for ancillary slides in case of questions.

**Pull request merged**
