### PR TITLE
2022.09: Iteration helpers as functions

### PR DESCRIPTION
**Pull request by rauschma**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Thanks! Holding off on this pending [IE status](https://github.com/tc39/Admin-and-Business/issues/257).

**Review by michaelficarra — APPROVED** [review]
Rebased and resolved conflicts. This invited expert has been approved. Merging.

**Comment by ljharb** [comment]
However, they haven’t yet signed the IPR form, which this PR should have waited on.

**Comment by rauschma** [comment]
I have, yesterday. I wasn’t aware that that was a missing step, but Rob Palmer reminded me and is now processing it.

**Comment by robpalme** [comment]
Axel is now approved as an Invited Expert

**Comment by ljharb** [comment]
Great, thanks!

**Pull request merged**
