### PR TITLE
✨ add TG reports, shorten CoC timebox

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Comment by michaelficarra** [comment]
Why don't we just remove the timebox for CoC updates? If there's an important update regarding the CoC, we're not going to cut it off for time.

**Comment by ctcpip** [comment]
@michaelficarra it's just a default value for the template and helps us when we make the schedule; the smaller timebox is more accurate for most cases.  of course we would change the time to accommodate whatever was needed, like we did for the last meeting.

**Comment by ctcpip** [comment]
@michaelficarra also: are you going to be available to give the the TG3 update for the September meeting?

**Comment by michaelficarra** [comment]
@ctcpip Sure.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
