### PR TITLE
Retract Date.parse

### PR DESCRIPTION
**Pull request by codehag**
Mozilla will be retracting this proposal. I am not sure I put it in the right bucket. Let me know!

### CODE REVIEW

**Comment by littledan** [comment]
Didn't @gibson042 take this on at the previous meeting?

**Comment by littledan** [comment]
Sorry, this was in the September meeting: @gibson042 presented on https://github.com/gibson042/ecma262-proposal-uniform-interchange-date-parsing . I think this proposal is working in the same space as the other proposal. It'd be great if you can work together on handing off the in-progress work.

**Comment by codehag** [comment]
Great! I was wondering about what was happening with the replacement for this. I am happy to have that replace this one. Should I update this to reflect that?

**Comment by littledan** [comment]
Well, I'm not sure if this needs to be brought to committee, or if you can just do this by updating the proposals repo and making the right note redirecting people from one repo to the other.

**Comment by chicoxyzzy** [comment]
Looks like this PR is outdated

**Pull request closed without merging**
