### PR TITLE
Remove day/time suggestions

### PR DESCRIPTION
**Pull request by littledan**
Thursday morning/afternoon for certain topics seems unrealistic; let's work out the details later.

### CODE REVIEW

**Comment by codehag** [comment]
@ljharb I am not available in the afternoon

**Comment by ljharb** [comment]
Obviously we have to work around schedule constraints, but confining lightning talks to Thursday was part of reformatting the agenda in #400.

**Comment by littledan** [comment]
We don't have anyone signed up for lightning talks at this point, so it seems pretty unrealistic to allocate a morning to it.

**Comment by ljharb** [comment]
I don't read the heading as allocating the morning to it, more saying that if any, that's when they'd be discussed.

**Comment by littledan** [comment]
I think the whole agenda is clearer if we remove these times; that's why the PR does it.

**Pull request merged**
