### PR TITLE
Add two agenda items

### PR DESCRIPTION
**Pull request by littledan**

### CODE REVIEW

**Comment by ljharb** [comment]
this was merged in the wrong order; i was in the middle of rebasing and merging all of these agenda items.

**Comment by michaelficarra** [comment]
Yeah I noticed there were a bunch out of order and wanted to get these pending ones in before sending a PR that sorts them appropriately again.

**Comment by ljharb** [comment]
they've already been fixed; i pushed a commit to master. i was in the process of ordering them correctly between each PR already.

**Comment by michaelficarra** [comment]
K. Thanks.

**Pull request merged**
